env:
  global:
    - VERSION=0.46.1
  matrix:
    - DOCKER_BUILD_DIR=./python-2.7
      IMAGE_NAME=dockerrepository/zappa:2.7
    # - DOCKER_BUILD_DIR=./python-3.6
    #   IMAGE_NAME=dockerrepository/zappa:3.6

sudo: required

services:
  - docker

script: bash build_image.sh


deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch:
      - master
      - test_travis

notifications:
  email: false