env:
  global:
    - VERSION=0.12.5
      PATH=https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb
  matrix:
    - DOCKER_BUILD_DIR=./python-2.7
      IMAGE_NAME=dockerrepository/wkhtmltopdf:2.7
    # - DOCKER_BUILD_DIR=./python-3.6
    #   IMAGE_NAME=dockerrepository/wkhtmltopdf:3.6

sudo: required

services:
  - docker

script: bash build_image.sh


deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch:
      - master

notifications:
  email: false